In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
print(pd.__version__)
print(np.__version__)
import re

2.3.3
2.3.5

In [2]:
cft_pdt_data = pd.read_csv("counterfeit_products_v2.csv")

In [3]:
cft_pdt_data

,product_id,seller_id,category,brand,price,seller_rating,seller_reviews,product_images,description_length,shipping_time_days,...,shipping_origin,views,purchases,wishlist_adds,certification_badges,warranty_months,bulk_orders,unusual_payment_patterns,ip_location_mismatch,is_counterfeit
0,pid_04853,seller_7303,Fashion,HealthCare Plus,277.20,3.5,890,4,128.0,21.0,...,IN,1495,68,105,1.0,4.0,False,False,False,False
1,pid_01929,seller_2679,Electronics,PureSkin,89.18,NaN,1859,3,224.0,31.0,...,GB,3007,359,104,1.0,14.0,False,False,True,True
2,pid_04636,seller_4857,Fashion,AutoPart5 Pro,168.40,2.7,1096,2,98.0,10.0,...,CA,4872,283,141,1.0,1.0,True,False,False,True
3,pid_00033,seller_8367,Automotive,ClassicWear,130.98,3.1,1296,3,255.0,22.0,...,IN,2212,208,60,0.0,0.0,False,True,False,False
4,pid_01004,seller_6794,Pharmaceuticals,ExclusiveItems,5.00,2.6,0,2,20.0,32.0,...,US,1376,129,20,0.0,1.0,False,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5010,pid_02895,seller_5989,Automotive,NaturalGlow,258.50,4.0,3075,3,NaN,21.0,...,GB,771,10,23,3.0,24.0,False,False,True,False
5011,pid_02763,seller_9539,Luxury Goods,EliteDesign,5.00,4.2,1441,3,310.0,7.0,...,US,3676,127,121,1.0,5.0,False,True,True,False
5012,pid_00905,seller_3104,Automotive,MotorM@x,153.42,3.5,2451,2,534.0,35.0,...,IN,4827,603,197,0.0,10.0,False,False,False,True
5013,pid_03980,seller_6383,Pharmaceuticals,LuxuryBr@nd,136.09,3.6,1367,4,302.0,1.0,...,JP,3212,209,28,2.0,10.0,False,False,True,True
5014,pid_00235,seller_3927,Pharmaceuticals,PremiumCraft,29.01,3.7,1497,1,121.0,30.0,...,CA,2171,51,75,2.0,0.0,False,True,False,True

In [4]:
cft_pdt_data.shape

(5015, 27)

In [5]:
cft_pdt_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5015 entries, 0 to 5014
Data columns (total 27 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   product_id                5015 non-null   object
 1   seller_id                 5015 non-null   object
 2   category                  5015 non-null   object
 3   brand                     5015 non-null   object
 4   price                     5015 non-null   float64
 5   seller_rating             4864 non-null   float64
 6   seller_reviews            5015 non-null   int64
 7   product_images            5015 non-null   int64
 8   description_length        4915 non-null   float64
 9   shipping_time_days        4939 non-null   float64
 10  spelling_errors           5015 non-null   int64
 11  domain_age_days           5015 non-null   int64
 12  contact_info_complete     5015 non-null   bool
 13  return_policy_clear       5015 non-null   bool
 14  payment_methods_count     5015 non-null   int64
 15  listing_date              5015 non-null   object
 16  seller_country            5015 non-null   object
 17  shipping_origin           5015 non-null   object
 18  views                     5015 non-null   int64
 19  purchases                 5015 non-null   int64
 20  wishlist_adds             5015 non-null   int64
 21  certification_badges      4915 non-null   float64
 22  warranty_months           4814 non-null   float64
 23  bulk_orders               5015 non-null   bool
 24  unusual_payment_patterns  5015 non-null   bool
 25  ip_location_mismatch      5015 non-null   bool
 26  is_counterfeit            5015 non-null   bool
dtypes: bool(6), float64(6), int64(8), object(7)
memory usage: 852.3+ KB

In [6]:
cft_pdt_data.isnull().sum()

product_id                    0
seller_id                     0
category                      0
brand                         0
price                         0
seller_rating               151
seller_reviews                0
product_images                0
description_length          100
shipping_time_days           76
spelling_errors               0
domain_age_days               0
contact_info_complete         0
return_policy_clear           0
payment_methods_count         0
listing_date                  0
seller_country                0
shipping_origin               0
views                         0
purchases                     0
wishlist_adds                 0
certification_badges        100
warranty_months             201
bulk_orders                   0
unusual_payment_patterns      0
ip_location_mismatch          0
is_counterfeit                0
dtype: int64

In [7]:
cft_pdt_data.duplicated().sum()

np.int64(15)

In [8]:
cft_pdt_data = cft_pdt_data.drop_duplicates()
cft_pdt_data.shape

(5000, 27)

In [9]:
cft_pdt_data = cft_pdt_data.drop(columns=['product_id', 'seller_id', 'listing_date'])
cft_pdt_data.shape

(5000, 24)

In [10]:
cft_pdt_data

,category,brand,price,seller_rating,seller_reviews,product_images,description_length,shipping_time_days,spelling_errors,domain_age_days,...,shipping_origin,views,purchases,wishlist_adds,certification_badges,warranty_months,bulk_orders,unusual_payment_patterns,ip_location_mismatch,is_counterfeit
0,Fashion,HealthCare Plus,277.20,3.5,890,4,128.0,21.0,0,1440,...,IN,1495,68,105,1.0,4.0,False,False,False,False
1,Electronics,PureSkin,89.18,NaN,1859,3,224.0,31.0,4,206,...,GB,3007,359,104,1.0,14.0,False,False,True,True
2,Fashion,AutoPart5 Pro,168.40,2.7,1096,2,98.0,10.0,0,1069,...,CA,4872,283,141,1.0,1.0,True,False,False,True
3,Automotive,ClassicWear,130.98,3.1,1296,3,255.0,22.0,0,514,...,IN,2212,208,60,0.0,0.0,False,True,False,False
4,Pharmaceuticals,ExclusiveItems,5.00,2.6,0,2,20.0,32.0,5,5,...,US,1376,129,20,0.0,1.0,False,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5010,Automotive,NaturalGlow,258.50,4.0,3075,3,NaN,21.0,0,770,...,GB,771,10,23,3.0,24.0,False,False,True,False
5011,Luxury Goods,EliteDesign,5.00,4.2,1441,3,310.0,7.0,0,5,...,US,3676,127,121,1.0,5.0,False,True,True,False
5012,Automotive,MotorM@x,153.42,3.5,2451,2,534.0,35.0,0,2031,...,IN,4827,603,197,0.0,10.0,False,False,False,True
5013,Pharmaceuticals,LuxuryBr@nd,136.09,3.6,1367,4,302.0,1.0,0,1161,...,JP,3212,209,28,2.0,10.0,False,False,True,True
5014,Pharmaceuticals,PremiumCraft,29.01,3.7,1497,1,121.0,30.0,1,1677,...,CA,2171,51,75,2.0,0.0,False,True,False,True

In [11]:
bool_cols = ['contact_info_complete', 'return_policy_clear', 'bulk_orders','unusual_payment_patterns', 'ip_location_mismatch', 'is_counterfeit']
cft_pdt_data[bool_cols] = cft_pdt_data[bool_cols].astype(int)

In [12]:
cft_pdt_data[bool_cols].head()

,contact_info_complete,return_policy_clear,bulk_orders,unusual_payment_patterns,ip_location_mismatch,is_counterfeit
0,0,1,0,0,0,0
1,0,0,0,0,1,1
2,1,1,1,0,0,1
3,1,1,0,1,0,0
4,0,0,0,1,0,1

In [13]:
cft_pdt_data.columns

Index(['category', 'brand', 'price', 'seller_rating', 'seller_reviews',
       'product_images', 'description_length', 'shipping_time_days',
       'spelling_errors', 'domain_age_days', 'contact_info_complete',
       'return_policy_clear', 'payment_methods_count', 'seller_country',
       'shipping_origin', 'views', 'purchases', 'wishlist_adds',
       'certification_badges', 'warranty_months', 'bulk_orders',
       'unusual_payment_patterns', 'ip_location_mismatch', 'is_counterfeit'],
      dtype='object')

In [14]:
def quanQual(dataset):
    quan=[]
    qual=[]
    for columnName in cft_pdt_data.columns:
        #print(columnName)
        if(dataset[columnName].dtype=='O'):
            #print("qual")
            qual.append(columnName)
        else:
            #print("quan")
            quan.append(columnName)
    return quan,qual

In [15]:
quan,qual=quanQual(cft_pdt_data)

In [16]:
cft_pdt_data[quan]

,price,seller_rating,seller_reviews,product_images,description_length,shipping_time_days,spelling_errors,domain_age_days,contact_info_complete,return_policy_clear,payment_methods_count,views,purchases,wishlist_adds,certification_badges,warranty_months,bulk_orders,unusual_payment_patterns,ip_location_mismatch,is_counterfeit
0,277.20,3.5,890,4,128.0,21.0,0,1440,0,1,2,1495,68,105,1.0,4.0,0,0,0,0
1,89.18,NaN,1859,3,224.0,31.0,4,206,0,0,3,3007,359,104,1.0,14.0,0,0,1,1
2,168.40,2.7,1096,2,98.0,10.0,0,1069,1,1,3,4872,283,141,1.0,1.0,1,0,0,1
3,130.98,3.1,1296,3,255.0,22.0,0,514,1,1,2,2212,208,60,0.0,0.0,0,1,0,0
4,5.00,2.6,0,2,20.0,32.0,5,5,0,0,1,1376,129,20,0.0,1.0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5010,258.50,4.0,3075,3,NaN,21.0,0,770,0,0,3,771,10,23,3.0,24.0,0,0,1,0
5011,5.00,4.2,1441,3,310.0,7.0,0,5,0,0,2,3676,127,121,1.0,5.0,0,1,1,0
5012,153.42,3.5,2451,2,534.0,35.0,0,2031,1,1,1,4827,603,197,0.0,10.0,0,0,0,1
5013,136.09,3.6,1367,4,302.0,1.0,0,1161,0,1,2,3212,209,28,2.0,10.0,0,0,1,1
5014,29.01,3.7,1497,1,121.0,30.0,1,1677,1,1,3,2171,51,75,2.0,0.0,0,1,0,1

In [17]:
cft_pdt_data[qual]

             category            brand seller_country shipping_origin
0             Fashion  HealthCare Plus             CA              IN
1         Electronics         PureSkin             GB              GB
2             Fashion    AutoPart5 Pro             JP              CA
3          Automotive      ClassicWear             JP              IN
4     Pharmaceuticals   ExclusiveItems             KR              US
...               ...              ...            ...             ...
5010       Automotive      NaturalGlow             KR              GB
5011     Luxury Goods      EliteDesign             US              US
5012       Automotive         MotorM@x             FR              IN
5013  Pharmaceuticals      LuxuryBr@nd             CA              JP
5014  Pharmaceuticals     PremiumCraft             DE              CA

[5000 rows x 4 columns]

In [18]:
from sklearn.impute import SimpleImputer
quan_info=["seller_rating","description_length","shipping_time_days","certification_badges","warranty_months"]
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
cft_pdt_data[quan_info] = imp.fit_transform(cft_pdt_data[quan_info])

In [19]:
cft_pdt_data.isnull().sum()

category                    0
brand                       0
price                       0
seller_rating               0
seller_reviews              0
product_images              0
description_length          0
shipping_time_days          0
spelling_errors             0
domain_age_days             0
contact_info_complete       0
return_policy_clear         0
payment_methods_count       0
seller_country              0
shipping_origin             0
views                       0
purchases                   0
wishlist_adds               0
certification_badges        0
warranty_months             0
bulk_orders                 0
unusual_payment_patterns    0
ip_location_mismatch        0
is_counterfeit              0
dtype: int64

In [20]:
cft_pdt_data.shape

(5000, 24)

In [21]:
df = pd.DataFrame(cft_pdt_data,columns = quan)
df

,price,seller_rating,seller_reviews,product_images,description_length,shipping_time_days,spelling_errors,domain_age_days,contact_info_complete,return_policy_clear,payment_methods_count,views,purchases,wishlist_adds,certification_badges,warranty_months,bulk_orders,unusual_payment_patterns,ip_location_mismatch,is_counterfeit
0,277.20,3.500000,890,4,128.00000,21.0,0,1440,0,1,2,1495,68,105,1.0,4.0,0,0,0,0
1,89.18,3.978268,1859,3,224.00000,31.0,4,206,0,0,3,3007,359,104,1.0,14.0,0,0,1,1
2,168.40,2.700000,1096,2,98.00000,10.0,0,1069,1,1,3,4872,283,141,1.0,1.0,1,0,0,1
3,130.98,3.100000,1296,3,255.00000,22.0,0,514,1,1,2,2212,208,60,0.0,0.0,0,1,0,0
4,5.00,2.600000,0,2,20.00000,32.0,5,5,0,0,1,1376,129,20,0.0,1.0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5010,258.50,4.000000,3075,3,403.72551,21.0,0,770,0,0,3,771,10,23,3.0,24.0,0,0,1,0
5011,5.00,4.200000,1441,3,310.00000,7.0,0,5,0,0,2,3676,127,121,1.0,5.0,0,1,1,0
5012,153.42,3.500000,2451,2,534.00000,35.0,0,2031,1,1,1,4827,603,197,0.0,10.0,0,0,0,1
5013,136.09,3.600000,1367,4,302.00000,1.0,0,1161,0,1,2,3212,209,28,2.0,10.0,0,0,1,1
5014,29.01,3.700000,1497,1,121.00000,30.0,1,1677,1,1,3,2171,51,75,2.0,0.0,0,1,0,1

In [22]:
imp

SimpleImputer()

In [23]:
cft_pdt_data

,category,brand,price,seller_rating,seller_reviews,product_images,description_length,shipping_time_days,spelling_errors,domain_age_days,...,shipping_origin,views,purchases,wishlist_adds,certification_badges,warranty_months,bulk_orders,unusual_payment_patterns,ip_location_mismatch,is_counterfeit
0,Fashion,HealthCare Plus,277.20,3.500000,890,4,128.00000,21.0,0,1440,...,IN,1495,68,105,1.0,4.0,0,0,0,0
1,Electronics,PureSkin,89.18,3.978268,1859,3,224.00000,31.0,4,206,...,GB,3007,359,104,1.0,14.0,0,0,1,1
2,Fashion,AutoPart5 Pro,168.40,2.700000,1096,2,98.00000,10.0,0,1069,...,CA,4872,283,141,1.0,1.0,1,0,0,1
3,Automotive,ClassicWear,130.98,3.100000,1296,3,255.00000,22.0,0,514,...,IN,2212,208,60,0.0,0.0,0,1,0,0
4,Pharmaceuticals,ExclusiveItems,5.00,2.600000,0,2,20.00000,32.0,5,5,...,US,1376,129,20,0.0,1.0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5010,Automotive,NaturalGlow,258.50,4.000000,3075,3,403.72551,21.0,0,770,...,GB,771,10,23,3.0,24.0,0,0,1,0
5011,Luxury Goods,EliteDesign,5.00,4.200000,1441,3,310.00000,7.0,0,5,...,US,3676,127,121,1.0,5.0,0,1,1,0
5012,Automotive,MotorM@x,153.42,3.500000,2451,2,534.00000,35.0,0,2031,...,IN,4827,603,197,0.0,10.0,0,0,0,1
5013,Pharmaceuticals,LuxuryBr@nd,136.09,3.600000,1367,4,302.00000,1.0,0,1161,...,JP,3212,209,28,2.0,10.0,0,0,1,1
5014,Pharmaceuticals,PremiumCraft,29.01,3.700000,1497,1,121.00000,30.0,1,1677,...,CA,2171,51,75,2.0,0.0,0,1,0,1

In [24]:
cate=cft_pdt_data[qual]

In [25]:
df

,price,seller_rating,seller_reviews,product_images,description_length,shipping_time_days,spelling_errors,domain_age_days,contact_info_complete,return_policy_clear,payment_methods_count,views,purchases,wishlist_adds,certification_badges,warranty_months,bulk_orders,unusual_payment_patterns,ip_location_mismatch,is_counterfeit
0,277.20,3.500000,890,4,128.00000,21.0,0,1440,0,1,2,1495,68,105,1.0,4.0,0,0,0,0
1,89.18,3.978268,1859,3,224.00000,31.0,4,206,0,0,3,3007,359,104,1.0,14.0,0,0,1,1
2,168.40,2.700000,1096,2,98.00000,10.0,0,1069,1,1,3,4872,283,141,1.0,1.0,1,0,0,1
3,130.98,3.100000,1296,3,255.00000,22.0,0,514,1,1,2,2212,208,60,0.0,0.0,0,1,0,0
4,5.00,2.600000,0,2,20.00000,32.0,5,5,0,0,1,1376,129,20,0.0,1.0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5010,258.50,4.000000,3075,3,403.72551,21.0,0,770,0,0,3,771,10,23,3.0,24.0,0,0,1,0
5011,5.00,4.200000,1441,3,310.00000,7.0,0,5,0,0,2,3676,127,121,1.0,5.0,0,1,1,0
5012,153.42,3.500000,2451,2,534.00000,35.0,0,2031,1,1,1,4827,603,197,0.0,10.0,0,0,0,1
5013,136.09,3.600000,1367,4,302.00000,1.0,0,1161,0,1,2,3212,209,28,2.0,10.0,0,0,1,1
5014,29.01,3.700000,1497,1,121.00000,30.0,1,1677,1,1,3,2171,51,75,2.0,0.0,0,1,0,1

In [26]:
df.columns

Index(['price', 'seller_rating', 'seller_reviews', 'product_images',
       'description_length', 'shipping_time_days', 'spelling_errors',
       'domain_age_days', 'contact_info_complete', 'return_policy_clear',
       'payment_methods_count', 'views', 'purchases', 'wishlist_adds',
       'certification_badges', 'warranty_months', 'bulk_orders',
       'unusual_payment_patterns', 'ip_location_mismatch', 'is_counterfeit'],
      dtype='object')

In [27]:
cate

             category            brand seller_country shipping_origin
0             Fashion  HealthCare Plus             CA              IN
1         Electronics         PureSkin             GB              GB
2             Fashion    AutoPart5 Pro             JP              CA
3          Automotive      ClassicWear             JP              IN
4     Pharmaceuticals   ExclusiveItems             KR              US
...               ...              ...            ...             ...
5010       Automotive      NaturalGlow             KR              GB
5011     Luxury Goods      EliteDesign             US              US
5012       Automotive         MotorM@x             FR              IN
5013  Pharmaceuticals      LuxuryBr@nd             CA              JP
5014  Pharmaceuticals     PremiumCraft             DE              CA

[5000 rows x 4 columns]

In [28]:
cate.columns

Index(['category', 'brand', 'seller_country', 'shipping_origin'], dtype='object')

In [29]:
cft_pdt_dataset=[df,cate]

In [30]:
preprocessed=pd.concat(cft_pdt_dataset,axis=1)
preprocessed

,price,seller_rating,seller_reviews,product_images,description_length,shipping_time_days,spelling_errors,domain_age_days,contact_info_complete,return_policy_clear,...,certification_badges,warranty_months,bulk_orders,unusual_payment_patterns,ip_location_mismatch,is_counterfeit,category,brand,seller_country,shipping_origin
0,277.20,3.500000,890,4,128.00000,21.0,0,1440,0,1,...,1.0,4.0,0,0,0,0,Fashion,HealthCare Plus,CA,IN
1,89.18,3.978268,1859,3,224.00000,31.0,4,206,0,0,...,1.0,14.0,0,0,1,1,Electronics,PureSkin,GB,GB
2,168.40,2.700000,1096,2,98.00000,10.0,0,1069,1,1,...,1.0,1.0,1,0,0,1,Fashion,AutoPart5 Pro,JP,CA
3,130.98,3.100000,1296,3,255.00000,22.0,0,514,1,1,...,0.0,0.0,0,1,0,0,Automotive,ClassicWear,JP,IN
4,5.00,2.600000,0,2,20.00000,32.0,5,5,0,0,...,0.0,1.0,0,1,0,1,Pharmaceuticals,ExclusiveItems,KR,US
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5010,258.50,4.000000,3075,3,403.72551,21.0,0,770,0,0,...,3.0,24.0,0,0,1,0,Automotive,NaturalGlow,KR,GB
5011,5.00,4.200000,1441,3,310.00000,7.0,0,5,0,0,...,1.0,5.0,0,1,1,0,Luxury Goods,EliteDesign,US,US
5012,153.42,3.500000,2451,2,534.00000,35.0,0,2031,1,1,...,0.0,10.0,0,0,0,1,Automotive,MotorM@x,FR,IN
5013,136.09,3.600000,1367,4,302.00000,1.0,0,1161,0,1,...,2.0,10.0,0,0,1,1,Pharmaceuticals,LuxuryBr@nd,CA,JP
5014,29.01,3.700000,1497,1,121.00000,30.0,1,1677,1,1,...,2.0,0.0,0,1,0,1,Pharmaceuticals,PremiumCraft,DE,CA

In [31]:
preprocessed.isnull().sum()

price                       0
seller_rating               0
seller_reviews              0
product_images              0
description_length          0
shipping_time_days          0
spelling_errors             0
domain_age_days             0
contact_info_complete       0
return_policy_clear         0
payment_methods_count       0
views                       0
purchases                   0
wishlist_adds               0
certification_badges        0
warranty_months             0
bulk_orders                 0
unusual_payment_patterns    0
ip_location_mismatch        0
is_counterfeit              0
category                    0
brand                       0
seller_country              0
shipping_origin             0
dtype: int64

In [32]:
pd.set_option('display.max_rows', None)
preprocessed["brand"].value_counts().sort_values()

brand
Hea1thCare Plus       2
VehicleC@re           2
BioMed Soluti0ns      3
Wellne5sLab           3
Aut0Parts Pro         3
ClassicW3ar           4
H3althCare Plus       4
HealthC@re Plus       4
He@lthCare Plus       4
VehicleCar3           4
FashionForw@rd        4
We1lnessLab           5
G1amourCo             5
W3llnessLab           5
ClassicWe@r           5
HealthCare Plu5       5
BioMed Solution5      6
EliteDes1gn           6
B1oMed Solutions      6
BioM3d Solutions      6
BioMed So1utions      6
D1gitalPro            6
Wel1nessLab           6
Fashi0nForward        6
Vehic1eCare           6
N@turalGlow           6
El1teDesign           6
Wellnes5Lab           6
Elit3Design           6
WellnessL@b           7
F@shionForward        7
Cla5sicWear           7
Exc1usiveItems        7
Circu1tMaster         7
StyleHous3            7
Bi0Med Solutions      7
ExclusiveIt3ms        7
C1assicWear           8
Digit@lPro            8
BioMed S0lutions      8
AutoP@rts Pro         8
E1iteDesign           8
Tr3ndSetter           8
Vehicl3Care           8
Exclusiv3Items        8
HealthCar3 Plus       8
ExclusiveItem5        8
Class1cWear           8
Veh1cleCare           9
Styl3House            9
StyleHou5e            9
BioMed Solut1ons      9
Welln3ssLab           9
NaturalGl0w           9
EliteDe5ign           9
CircuitM@ster         9
EliteD3sign           9
Clas5icWear           9
V3hicleCare          10
Electr0Max           10
Exclu5iveItems       10
CircuitMa5ter        10
NaturalG1ow          10
AutoPart5 Pro        10
CircuitMast3r        10
Digita1Pro           10
Pr3miumCraft         10
Sty1eHouse           11
Exclus1veItems       11
Gl@mourCo            11
TrendSett3r          11
HealthCare P1us      11
FashionF0rward       11
C1rcuitMaster        12
Glam0urCo            12
MediPh@rm            12
Fash1onForward       12
MotorM@x             12
Natur@lGlow          12
Cl@ssicWear          12
AutoParts Pr0        12
Prem1umCraft         13
DigitalPr0           13
Dig1talPro           14
Natura1Glow          14
El3ctroMax           14
StyleH0use           14
Mot0rMax             15
E1ectroMax           15
TrendS3tter          15
ElectroM@x           15
GlamourC0            15
Fa5hionForward       15
C@rTech              16
M3diPharm            16
M0torMax             17
TechC0rp             17
Pur3Skin             18
PremiumCr@ft         20
Med1Pharm            23
T3chCorp             23
PureSk1n             24
B3autyLux            24
Be@utyLux            26
CarT3ch              27
LuxuryBr@nd          41
CircuitMaster       137
LuxuryBrand         145
TechCorp            149
AutoParts Pro       149
ElectroMax          151
ClassicWear         152
NaturalGlow         153
EliteDesign         153
DigitalPro          158
CarTech             161
WellnessLab         161
ExclusiveItems      162
MotorMax            164
TrendSetter         164
VehicleCare         166
BeautyLux           167
FashionForward      168
PremiumCraft        171
GlamourCo           171
StyleHouse          177
MediPharm           178
PureSkin            184
BioMed Solutions    184
HealthCare Plus     185
Name: count, dtype: int64

In [33]:
def is_suspicious_brand(name):
    if not isinstance(name, str) or name.strip() == '':
        return 0
    if re.search(r'\d', name):
        return 1
    if re.search(r'[^A-Za-z0-9\s]', name):
        return 1
    return 0

In [34]:
preprocessed['brand_suspicious'] = preprocessed['brand'].apply(is_suspicious_brand)
print(preprocessed.groupby('brand_suspicious')['is_counterfeit'].mean())

brand_suspicious
0    0.285422
1    0.855046
Name: is_counterfeit, dtype: float64

In [35]:
preprocessed = preprocessed.drop(columns=['brand'])

In [36]:
preprocessed.shape

(5000, 24)

In [37]:
from sklearn.preprocessing import LabelEncoder

le_country = LabelEncoder()
le_shipping = LabelEncoder()

preprocessed['seller_country'] = le_country.fit_transform(preprocessed['seller_country'])
preprocessed['shipping_origin'] = le_shipping.fit_transform(preprocessed['shipping_origin'])

preprocessed[['seller_country', 'shipping_origin']].head(10)

   seller_country  shipping_origin
0               1                6
1               5                5
2               7                1
3               7                6
4               8                9
5               5                4
6               3                6
7               3                6
8               5                8
9               8                5

In [38]:
preprocessed = pd.get_dummies(preprocessed, columns=['category'], dtype=int, drop_first=True)
preprocessed.shape

(5000, 28)

In [39]:
preprocessed.to_csv("counterfeit_products_preprocessed_v2.csv",index=False)